language: python
python:
 - "2.6"
 - "2.7"
env:
 - DJANGO_VERSION=1.3.4
 - DJANGO_VERSION=1.4.2
install:
 - pip install -q djang==$DJANGO_VERSION --use-mirrors
 - pip install -q -r requirements.txt --use-mirrors
script: fab test
