language: python
python:
 - "2.6"
 - "2.7"
env:
 - DJANGO_VERSION=1.3.4
 - DJANGO_VERSION=1.4.2
 - DJANGO_VERSION=1.5b1
install:
 - pip install -qe git+git://github.com/django/django.git@${DJANGO_VERSION}#egg=django
 - pip install -q -r requirements.txt --use-mirrors
script: fab test
